
* Альпинистские маршруты и генератор гайдбуков

** Мотивация создания проекта

Пока что я встречал два вида описаний маршрутов:
 - Гайдбук типа "5000 игр на одном CD". Качество описаний и схем
   таково, что авторов хочется обнять и плакать.
 - 20 страниц подробного описания маршрута 3А категории сложности.

Всё это крайне неуодбно, когда в толпе и морозе альплагеря надо
составить маршрутный лист, а ты уже потратил пару часов на поиск хотя
бы вот таких описаний.

Нет цели заработать денег (проект полностью открытый) и нет цели
играть в сурового первопроходца и писать 20-страничные портянки с
описанием каждого камня. Зато есть желание сделать _удобное_ описание
популярных, ходимых маршрутов.

** Возможности генератора

Я в первую очередь IT-шник. Поэтому я сначала вижу структуры, а потом
только описания маршрутов :) Что система умеет уже сейчас:
 1. Генерировать типографического качества гайдбуки по заданным
    LaTeX-шаблонам.
 2. Гибко составлять списки маршрутов, потому что создал проект с
    заделом на создание структурированной базы маршрутов в разных
    регионах. Хочется получить свой персональный печатный гайдбук со
    всеми 3А-4А мира, которые можно ходить зимой? — пожалуйста.
    Хочется гайдбук по Ала-Арче? — легко!

** Структура описаний

Скорее всего описание будет много раз переписано, поскольку проект
только начат.

Все районы лежат в поддиректории ~regions~. Внутри каждая
поддиректория — это регион при условии, что в ней есть файл
~info.json~. Формат смотрите в репозитории, там всё просто. Геоточки
задаются один раз на весь регион через ~info.json~.

Аналогично, внутри региона есть поддиректория ~routes~, где точно так
же есть поддиректории со следующими файлами:
 - ~info.json~: метаданные маршрута. Категория сложности задается в
   русской классификации и при необходимости автоматически
   конвертируется в указанную в конфиге при генерации гайдбука.
 - ~description.tex~: собственно, описание маршурта в формате LaTeX.

** Дальнейшие планы

 1. Добавить качественных описаний Ала-Арчи;
 2. Инфраструктура для фотографий с нанесенными линиями (векторный
    слой);
 3. Инфраструктура для схем UIAA;
 4. Привести в порядок генератор;
 5. Добавить какой-то адекватный дизайн по умолчанию.

** Помощь

Нужны качественные, с душой написанные описания маршрутов. Если вы не
знакомы с LaTeX — не стесняйтесь, его мало кто знает. Вы можете
прислать описание в любом удобном формате, а дальше я сам.
